### ISSUE TITLE
Modernize Organize Series codebase.

### ISSUE THREAD

**Issue by nerrad** [publishpress/publishpress-series#28]
The current organize series codebase has been in place for a number of years now and is starting to show its age.  I haven't spent much time on it because of my increasing work with development for clients.  Fortunately Organize Series has aged well in _spite_ of its codebase.  Some goals with this update will be:

* [x] Require PHP5.6+  (PHP5.2 is less than 2% of the Organize Series user base now and hosts upgrading users are usually updated directly to PHP7 so we should be fine with this bump)
* [x] Implement composer for autoloaders.
* [x] Use namespaces.
* [ ] Updating JS.
* [ ] Updating Series taxonomy/term pages.
* [ ] Updating series options pages.
* [ ] Adding unit tests (and maybe acceptance tests)
* [ ] Implementing a build/release system to automate releases to WP.org

Other things:

- I _am_ going to try to preserve back compat as much as possible by keeping existing template functions that return the expected values.  However internally this does mean some existing filters/actions could change (again with back compat where possible).  There likely will be some deprecated things.
- Some of this will likely impact add-on development as well.
- There _could_ be a migration path that will bring series icons into the WP attachments system (instead of a custom table) and link via the new WP term_meta api.
- [Gutenberg](https://github.com/WordPress/gutenberg) is heading for WP core (likely first or second quarter 2018).  So I think it'd be beneficial to investigate what an Organize Series block might look like in it.  We probably could have various blocks (blocks for where the series toc displays, series navigation, series meta, series image etc).  This would also be something good to look into updating the Organize Series Shortcodes Extension to use gutenberg blocks.

**Comment by nerrad** [comment]
I'm starting on some of this with #29 so it's looking like the next release of Organize Series (priori to what this ticket is for) will _require_ PHP5.3.  I might have to do an interim release of OrganizeSeries before #29 is out the door to prep people.
